language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"

matrix:
  include:
    - stage: codecheck
      python: 3.8
      install:
        - pip install flake8
      script:
        - flake8 sqlparse
      after_success: skip

install:
  - pip install -Uq pytest pytest-cov codecov
  - pytest --version

script:
  - pytest --cov=sqlparse

after_success:
    - codecov
